backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "content"
    label: "Inhaltsseite"
    folder: "src/pages/content"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "content-page"}
      - {label: Titel , name: title, widget: string}
      - {label: Subheading, name: subheading, widget: string}
      - {label: Titelbild, name: titleimage, widget: object, fields: [
          {label: Image, name: image, widget: image}, 
          {label: Alt, name: alt, widget: string}
        ]}
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Quote, name: quote, widget: object, fields: [{label: Text, name: text, widget: "text"}, {label: Author, name: author, widget: string}]} 
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: Titelbild, name: titleimage, widget: object, fields: [
              {label: Image, name: image, widget: image}, 
              {label: Alt, name: alt, widget: string}
            ]}
          - {label: Zeitstrahl, name: history, widget: list, fields: [
              {label: Bild, name: historyimage, widget: object, fields: [
                {label: Image, name: image, widget: image}, 
                {label: Alt, name: alt, widget: string}
              ]},
              {label: Titel, name: title, widget: string},
              {label: Beschreibung, name: description, widget: "markdown"}
            ]}
          - {label: "Contact Block", name: contactblock, widget: object, fields: [
              {label: Adresse, name: adress, widget: object, fields: [
                {label: Icon, name: image, widget: image},
                {label: "Straße", name: street, widget: string},
                {label: "PLZ & Ort", name: city, widget: string}
              ]},
              {label: "Telefon & Fax", name: numbers, widget: object, fields: [
                {label: Icon, name: image, widget: image},
                {label: "Telefon", name: phone, widget: string},
                {label: "Fax", name: fax, widget: string}
              ]},
              {label: "Internet Adressen", name: webadress, widget: object, fields: [
                {label: Icon, name: image, widget: image},
                {label: "E-Mail", name: mail, widget: string},
                {label: "Webseite", name: web, widget: string}
              ]},
              {label: "Öffnungszeiten", name: openhours, widget: object, fields: [
                {label: "Regulär", name: regularhours, widget: "text"},
                {label: "Zusätzliche Infos", name: specialinfo, widget: "text"}
              ]},
              {label: "Öffnungszeiten", name: openinghours, widget: list, fields: [
                  {label: "Von (Wochentag)", name: daysbegin, widget: select, options: ["Montag", "Dienstag", "Mittwoch", "Donnerstag", "Freitag", "Samstag"], default: ["Montag"] },
                  {label: "Bis (Wochentag)", name: daysend, widget: select, options: ["Montag", "Dienstag", "Mittwoch", "Donnerstag", "Freitag", "Samstag"], default: ["Samstag"] },
                  {label: "Von (Uhrzeit)", name: timebegin, widget: number, default: 10, value_type: "int", min: 0, max: 23 },
                  {label: "Bis (Uhrzeit)", name: timeend, widget: number, default: 16, value_type: "int", min: 0, max: 23 },

              ]}
            ]}
      - file: "src/pages/products/index.md"
        label: "Products Page"
        name: "products"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Einführungstext, name: description, widget: markdown}
